### PR TITLE
12 - implement create new chat and get messages

### PR DESCRIPTION
**Pull request by flashback2k14**
I have forced 2 issues:
- after creating a new chat - the new chat doesn't synchronize to the other clients!?
- add new Message to a new created chat showing up multiple times!? 
  - maybe unregister an eventbus handler for the old chat before changing to an new chat resolve the problem?

@lyio @hetec for review

### CODE REVIEW

**Comment by flashback2k14** [comment]
- 1 issue: we need another eventbus that push the new created chats to The Clients
- 2 issue: WORKAROUND: collect all messages in an array an check if The message is already displayed

@lyio @hetec

**Comment by flashback2k14** [comment]
i dont't know why, but today all works great. :-)

**Comment by flashback2k14** [comment]
HELP NEEDED!!!! i have no idea what the problem is!?!?

@lyio @hetec

**Comment by patrick-hebner** [comment]
This woks for me. Meaning there are no duplicate chat messages anymore. Hi hope it works for you to. But there is still the problem that new chats are not published to the client.

**Comment by flashback2k14** [comment]
Finally all working as expected!

@hetec @lyio for review

**Pull request merged**
